title: Waterproofing Auckland for 20 years
email: admin@totalwp.co.nz
description: > # this means to ignore newlines until "baseurl:"
  Professional waterproofing installation, service and advice. Greater Auckland Area and Western Bay of Plenty. Various waterproofing systems. Residential and commercial buildings. New construction or renovation. We waterproof above and below ground, sealing, tanking, pools, roofs, decks, bathrooms and other interior wet areas. No job is too big or too small.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://totalwp.co.nz" # the base hostname & protocol for your site, e.g. http://example.com

phone: "09 411 9501"
mobile: "021 626 518"
bop_phone: "07 863 5106"

address: |
  Total Waterproofing (2005) Ltd
  PO Box 56 Waihi Beach,
  Waihi Beach 3642, New Zealand

sales_email: tony@totalwp.co.nz
service_email: dave@totalwp.co.nz

# Build settings
markdown: kramdown
